In [2]:
import open3d as o3d
import numpy as np
import os
import glob
import pandas as pd
import pymeshlab as pml
import time
import matplotlib as plt

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [5]:
from scipy.stats import wasserstein_distance
from emd import get_emd

In [6]:
wasserstein_distance([0, 1, 3], [5, 6, 8])

5.0

In [7]:
df = pd.read_pickle("./normalized_features_final.pkl")
df.reset_index(drop=True, inplace=True)

In [5]:
df

class                              path         V         S  \
1   AircraftBuoyant  ./features/AircraftBuoyant\m1337  4.100846  0.214806   
1   AircraftBuoyant  ./features/AircraftBuoyant\m1338  4.728118  0.540607   
1   AircraftBuoyant  ./features/AircraftBuoyant\m1339  0.087864  0.155798   
1   AircraftBuoyant  ./features/AircraftBuoyant\m1340  0.219291 -0.646455   
1   AircraftBuoyant  ./features/AircraftBuoyant\m1341 -0.458655 -0.605102   
..              ...                               ...       ...       ...   
1        WheelChair      ./features/WheelChair\D00687 -0.257985 -0.136291   
1        WheelChair      ./features/WheelChair\D00720  0.415856 -0.265226   
1        WheelChair      ./features/WheelChair\D00782  0.330954 -0.270341   
1        WheelChair      ./features/WheelChair\D00821  0.315740 -0.136219   
1        WheelChair      ./features/WheelChair\D00846  0.174475 -0.376880   

           c         D         R         E         C  \
1  -0.021151 -0.431171  1.524371  4.945361  1.790998   
1  -0.021151 -0.117928  1.525120  3.309235  1.818866   
1  -0.021151 -0.690660  0.052891  0.829243  0.072976   
1  -0.021151 -0.689441  0.445397 -0.294062  0.667100   
1  -0.021151 -0.691012 -1.082039 -0.191202 -1.437485   
..       ...       ...       ...       ...       ...   
1  -0.021151 -0.318480 -0.355524  0.236439 -0.413690   
1  -0.021151 -0.563298  0.443687  0.331357  0.558552   
1  -0.021151 -0.133080  0.251680  0.460616  0.345153   
1  -0.021151 -0.316797  0.369517  0.233050  0.444380   
1  -0.021151 -0.357894  0.125495  0.981745  0.168650   

                                                   A3  \
1   [0.000726, 0.002233, 0.003601, 0.004919, 0.006...   
1   [0.000905, 0.002401, 0.003699, 0.004898, 0.006...   
1   [0.002045, 0.005137, 0.007327, 0.009413, 0.011...   
1   [0.006895, 0.012267, 0.016517, 0.020126, 0.023...   
1   [0.004708, 0.010527, 0.014929, 0.01883, 0.0220...   
..                                                ...   
1   [0.010272, 0.014989, 0.015033, 0.013491, 0.013...   
1   [0.00313, 0.006494, 0.008935, 0.010701, 0.0120...   
1   [0.001609, 0.002788, 0.003763, 0.004353, 0.004...   
1   [0.010325, 0.015111, 0.014943, 0.013719, 0.012...   
1   [0.006151, 0.01067, 0.011006, 0.010847, 0.0106...   

                                                   D1  \
1   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
1   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
1   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
1   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
1   [0.0, 0.0024, 0.0046, 0.0049, 0.0032, 0.0064, ...   
..                                                ...   
1   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
1   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0003, ...   
1   [0.0, 0.0002, 0.0001, 0.0001, 0.0001, 0.0001, ...   
1   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
1   [0.0, 0.0001, 0.0001, 0.0002, 0.0007, 0.0005, ...   

                                                   D2  \
1   [0.0, 0.0004, 0.00058, 0.0012, 0.00102, 0.0015...   
1   [0.00013, 0.00038, 0.0006, 0.001, 0.00152, 0.0...   
1   [0.00013, 0.0008, 0.00136, 0.00168, 0.0022, 0....   
1   [0.00068, 0.00277, 0.00381, 0.00512, 0.00633, ...   
1   [0.00058, 0.0018, 0.00276, 0.00355, 0.00449, 0...   
..                                                ...   
1   [0.00213, 0.00465, 0.00622, 0.00658, 0.00785, ...   
1   [0.00059, 0.00119, 0.00229, 0.0039, 0.0037, 0....   
1   [0.00031, 0.00155, 0.00234, 0.00289, 0.00334, ...   
1   [0.00276, 0.00394, 0.00617, 0.00705, 0.00779, ...   
1   [0.00121, 0.00299, 0.00463, 0.00596, 0.00696, ...   

                                                   D3  \
1   [2e-06, 5e-06, 1.9e-05, 5.7e-05, 0.000109, 0.0...   
1   [3e-06, 1.6e-05, 4.9e-05, 0.000101, 0.000188, ...   
1   [6e-06, 1.8e-05, 5.9e-05, 0.000113, 0.00024, 0...   
1   [4e-06, 6.5e-05, 0.000188, 0.000423, 0.000712,...   
1   [8e-06, 3.7e-05, 0.000104, 0.000253, 0.000482,...   
..                 

In [8]:
def w_dist(a,b):
    return wasserstein_distance(a,b)*1000

In [9]:
valdf = df[['A3', 'D1', 'D2', 'D3', 'D4']]

In [10]:
newobj = df.iloc()[1300][['A3', 'D1', 'D2', 'D3', 'D4']]
newobj

A3    [0.005445, 0.012587, 0.016992, 0.020727, 0.023...
D1    [0.0, 0.0006, 0.0032, 0.0038, 0.0045, 0.0036, ...
D2    [0.00047, 0.0017, 0.0029, 0.00443, 0.00618, 0....
D3    [2.4e-05, 0.000276, 0.000935, 0.002035, 0.0036...
D4    [5e-05, 0.000375, 0.00089, 0.001752, 0.002815,...
Name: 1300, dtype: object

In [69]:
w1=1;w2=1;w3=1;w4=1;w5=1
weights = np.array([w1,w2,w3,w4,w5])

In [70]:
weighted_sums = np.array([])
for index, row in valdf.iterrows():
        # print(valdf.columns[0])
        values = np.array([])
        for col in valdf.columns:
            dist = w_dist(newobj[col],row[col])
            # dist = get_emd(newobj[col],row[col])

            values = np.append(values, dist)
        weighted_sum = np.dot(values, weights)
        weighted_sums = np.append(weighted_sums, weighted_sum)
        # print(weighted_sum)

In [71]:
lowest_indices = np.argsort(weighted_sums)[:10]

lowest_values = weighted_sums[lowest_indices]

print("5 Lowest Values:", lowest_values)
print("Indices of the 5 Lowest Values:", lowest_indices)


5 Lowest Values: [0.         2.11851115 2.97657638 3.08118894 3.20097564 3.38957091
 3.42135312 3.63629361 3.72862602 3.84290286]
Indices of the 5 Lowest Values: [1300 1318 1309 1351 1364 1335  918 1310 1284 1361]


In [72]:
df.iloc[lowest_indices]["class"]

1           Jet
1           Jet
1           Jet
1           Jet
1           Jet
1           Jet
1    Helicopter
1           Jet
1           Jet
1           Jet
Name: class, dtype: object

In [ ]:
df[df["class"]=="Vase"]

In [10]:
df[df.apply(lambda x: x.isnull().any(), axis=1)]


Empty DataFrame
Columns: [class, path, V, S, c, D, R, E, C, A3, D1, D2, D3, D4]
Index: []

In [11]:
def has_nan_in_list(row):
    return any(pd.isna(x) for x in row['D1'])
df_has_nan = df.apply(has_nan_in_list, axis=1)
df[df_has_nan]

Empty DataFrame
Columns: [class, path, V, S, c, D, R, E, C, A3, D1, D2, D3, D4]
Index: []

In [65]:
import sys
sys.path.append('../preprocessing')
from viz import viz_mesh

In [85]:
viz_mesh("../resampledPML//Chess\m1591.obj"	)

In [75]:
def give_random_triplets(input=range(10), samples=10):
    return np.random.choice(input, size=(samples, 3), replace=True)

random_triplets = give_random_triplets(input=range(1000), samples=1000000)
random_triplets

array([[756, 820, 553],
       [ 86, 287,  27],
       [226, 402, 564],
       ...,
       [355, 783, 267],
       [586,  81, 968],
       [387, 647, 719]])

In [76]:
equal_indices = np.where((random_triplets[:, 0] == random_triplets[:, 1]) | (random_triplets[:, 1] == random_triplets[:, 2]) | (random_triplets[:, 0] == random_triplets[:, 2]))
equal_indices[0]

array([   454,    519,    583, ..., 999291, 999627, 999783], dtype=int64)

In [77]:
random_triplets[equal_indices] = give_random_triplets(samples=random_triplets[equal_indices].shape[0] )


In [194]:
random_triplets = give_random_triplets(input=range(7000), samples=1000000)
equal_indices = np.where((random_triplets[:, 0] == random_triplets[:, 1]) | (random_triplets[:, 1] == random_triplets[:, 2]) | (random_triplets[:, 0] == random_triplets[:, 2]))
while equal_indices[0].size > 0:
    random_triplets[equal_indices] = give_random_triplets(samples=random_triplets[equal_indices].shape[0] )
    equal_indices = np.where((random_triplets[:, 0] == random_triplets[:, 1]) | (random_triplets[:, 1] == random_triplets[:, 2]) | (random_triplets[:, 0] == random_triplets[:, 2]))

random_triplets


58.2 ms ± 4.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Accuracy measures

In [196]:
def get_top_k_results(newobj, k=10):
    w1=1;w2=1;w3=1;w4=4;w5=3
    weights = np.array([w1,w2,w3,w4,w5])
    weighted_sums = np.array([])
    for index, row in valdf.iterrows():
        # print(valdf.columns[0])
        values = np.array([])
        for col in valdf.columns:
            dist = w_dist(newobj[col],row[col])
            # dist = get_emd(newobj[col],row[col])

            values = np.append(values, dist)
        weighted_sum = np.dot(values, weights)
        weighted_sums = np.append(weighted_sums, weighted_sum)
        # print(weighted_sum)
        lowest_indices = np.argsort(weighted_sums)[:k+1]

        lowest_values = weighted_sums[lowest_indices]

    print("5 Lowest Values:", lowest_values)
    print("Indices of the 5 Lowest Values:", lowest_indices)
    return lowest_indices, lowest_values


In [15]:
df.columns[9:]

Index(['A3', 'D1', 'D2', 'D3', 'D4'], dtype='object')

In [97]:
def get_top_k_results_allfeatures(newobj, k=10):
    w0=5;w1=1;w2=1;w3=1;w4=1;w5=1
    weights = np.array([w0,w1,w2,w3,w4,w5])
    weighted_sums = np.array([])
    for index, row in df.iterrows():
        # print(valdf.columns[0])
        values = np.array([])
        # dist = euclidean_distance(newobj,row)
        # values = np.append(values, dist)
        dist2 = cosine_distance(newobj,row)
        values = np.append(values, dist2)
            
        for col in df.columns[9:]:
            dist3 = w_dist(newobj[col],row[col])
            # dist = get_emd(newobj[col],row[col])

            values = np.append(values, dist3)
        weighted_sum = np.dot(values, weights)
        weighted_sums = np.append(weighted_sums, weighted_sum)
        # print(weighted_sum)
        lowest_indices = np.argsort(weighted_sums)[:k+1]

        lowest_values = weighted_sums[lowest_indices]

    print("5 Lowest Values:", lowest_values)
    print("Indices of the 5 Lowest Values:", lowest_indices)
    return lowest_indices, lowest_values


In [94]:

newobj = df.iloc()[130]#[['A3', 'D1', 'D2', 'D3', 'D4']]
newobj

class                                              Biplane
path                             ./features/Biplane\D00410
V                                                -0.073661
S                                                -0.498022
c                                                -0.021151
D                                                -0.654631
R                                                -0.269601
E                                                -0.535418
C                                                -0.374068
A3       [0.00518, 0.011636, 0.014856, 0.018058, 0.0208...
D1       [0.0001, 0.0001, 0.0003, 0.0008, 0.0021, 0.001...
D2       [0.00052, 0.00179, 0.0035, 0.00489, 0.00652, 0...
D3       [1.7e-05, 0.0001, 0.000383, 0.000934, 0.001647...
D4       [0.000216, 0.00022, 0.000556, 0.001181, 0.0018...
Name: 130, dtype: object

In [95]:
lowest_indices, lowest_values = get_top_k_results_allfeatures(newobj=newobj)

5 Lowest Values: [0.         3.20105525 3.23270059 3.2584804  3.38854713 3.51740614
 3.59079407 3.64372214 3.67745789 3.75281822 3.91014752]
Indices of the 5 Lowest Values: [ 130 1216 1224  994 1131 2271  962  146  645 1201 1002]


In [96]:
df.iloc[lowest_indices]["class"]

130        Biplane
1216        Insect
1224        Insect
994          House
1131      Humanoid
2271          Tool
962     Helicopter
146        Biplane
645      DeskPhone
1201      Humanoid
1002         House
Name: class, dtype: object

In [99]:
import pandas as pd
import random

# Create an empty dictionary to store the random indices
random_indices_dict = {}
indices_arr = np.array([],dtype=int)
# Group the DataFrame by the "class" column
grouped = df.groupby('class')

# Iterate over each group and select two different random indices for each
for name, group in grouped:
    indices = group.index.tolist()
    newvals = random.sample(indices, min(2, len(indices)))
    random_indices_dict[name] = newvals
    indices_arr = np.append(indices_arr,newvals)

# Display the random indices for each distinct class
print(random_indices_dict)
print(indices_arr)


{'AircraftBuoyant': [3, 7], 'Apartment': [17, 21], 'AquaticAnimal': [40, 65], 'Bed': [78, 81], 'Bicycle': [104, 99], 'Biplane': [160, 147], 'Bird': [208, 193], 'Bookset': [217, 218], 'Bottle': [242, 258], 'BuildingNonResidential': [271, 276], 'Bus': [308, 318], 'Car': [387, 359], 'Cellphone': [420, 417], 'Chess': [469, 442], 'City': [484, 496], 'ClassicPiano': [514, 508], 'Computer': [548, 540], 'ComputerKeyboard': [563, 557], 'Cup': [586, 587], 'DeskLamp': [609, 632], 'DeskPhone': [639, 636], 'Door': [663, 673], 'Drum': [698, 702], 'Fish': [717, 735], 'FloorLamp': [744, 754], 'Glasses': [773, 775], 'Guitar': [799, 796], 'Gun': [847, 842], 'Hand': [864, 863], 'Hat': [912, 899], 'Helicopter': [943, 935], 'House': [971, 991], 'HumanHead': [1040, 1019], 'Humanoid': [1188, 1176], 'Insect': [1230, 1222], 'Jet': [1364, 1290], 'Knife': [1411, 1422], 'MilitaryVehicle': [1452, 1446], 'Monitor': [1464, 1474], 'Monoplane': [1481, 1496], 'Motorcycle': [1522, 1500], 'Mug': [1549, 1527], 'MultiSeat'

In [195]:
get_top_k_results(newobj, k = 10)

5 Lowest Values: [0.         2.6673     3.0845001  3.16317584 3.19272594 3.20122
 3.26587334 3.29074614 3.32684614 3.39054438 3.39365327]
Indices of the 5 Lowest Values: [2461 2458 2334 1982 1984  876 1974  897 1633 1555 1590]


(array([2461, 2458, 2334, 1982, 1984,  876, 1974,  897, 1633, 1555, 1590],
       dtype=int64),
 array([0.        , 2.6673    , 3.0845001 , 3.16317584, 3.19272594,
        3.20122   , 3.26587334, 3.29074614, 3.32684614, 3.39054438,
        3.39365327]))

In [100]:
totalcorrect = 0
total = 0
for i in indices_arr:
    newobj = df.iloc()[i]
    # lowest_indices, lowest_values = get_top_k_results(newobj, k = 10)
    lowest_indices, lowest_values = get_top_k_results_allfeatures(newobj, k = 10)

    y = df.iloc[lowest_indices[0]]["class"]
    correct = 0
    for ind in lowest_indices[1:]:
        if df.iloc[ind]["class"] == y:
            correct += 1 
    totalcorrect += correct
    total += len(lowest_indices[1:])

5 Lowest Values: [5.55111512e-16 5.36048538e+00 5.79973190e+00 6.04039481e+00
 6.33432575e+00 6.46676380e+00 6.48293472e+00 6.57762047e+00
 6.60892444e+00 6.62413100e+00 6.65529732e+00]
Indices of the 5 Lowest Values: [   3  630 1746  752 1842 1843 1108  748 2399 2070  625]
5 Lowest Values: [1.11022302e-15 8.03586726e+00 8.17512321e+00 8.76033016e+00
 9.03558292e+00 9.61681450e+00 9.75431794e+00 9.76984376e+00
 9.90122452e+00 9.95181537e+00 1.00554046e+01]
Indices of the 5 Lowest Values: [   7 2411 1031 2413 2446  744    8 1038 1054  273    6]
5 Lowest Values: [-1.11022302e-15  5.65548191e+00  5.69391318e+00  5.97937661e+00
  6.41464277e+00  6.43408520e+00  6.45475202e+00  6.46951514e+00
  6.57519949e+00  6.60154189e+00  6.65202777e+00]
Indices of the 5 Lowest Values: [  17 2453 1828 1505  893  433  469 1001  865  457  438]
5 Lowest Values: [-1.11022302e-15  6.40974751e+00  6.92660803e+00  7.39312765e+00
  7.42837362e+00  7.51787565e+00  7.57628106e+00  7.74173274e+00
  7.83010295e+00 

In [ ]:
totalcorrect, total, totalcorrect/ total

In [199]:
totalcorrect, total, totalcorrect/ total

(209, 1380, 0.15144927536231884)

In [192]:
totalcorrect, total, totalcorrect/ total

(238, 1380, 0.17246376811594202)

In [188]:
df.iloc[lowest_indices]

class                       path         V         S         c  \
100   Bicycle  ./features/Bicycle\D00462  0.015860 -0.558199 -0.021151   
102   Bicycle  ./features/Bicycle\D00536 -0.003958 -0.594845 -0.021151   
1465  Monitor  ./features/Monitor\D00391 -0.179488  1.204441 -0.021151   
108   Bicycle  ./features/Bicycle\D00750  0.100926 -0.272764 -0.021151   
114   Bicycle  ./features/Bicycle\D00974 -0.024465 -0.548177 -0.021151   
96    Bicycle  ./features/Bicycle\D00033  0.011966 -0.672358 -0.021151   
115   Bicycle   ./features/Bicycle\m1472  0.001595 -0.627271 -0.021151   
106   Bicycle  ./features/Bicycle\D00621  0.045538 -0.656544 -0.021151   
104   Bicycle  ./features/Bicycle\D00558 -0.014542 -0.538586 -0.021151   
99    Bicycle  ./features/Bicycle\D00078  0.067563 -0.551459 -0.021151   
95    Bicycle  ./features/Bicycle\D00016  0.013289 -0.658291 -0.021151   

             D         R         E         C  \
100  -0.530023 -0.014967 -0.675910 -0.021856   
102  -0.509049 -0.024217 -0.458325 -0.038430   
1465  0.852796 -0.389738 -0.702152 -0.545376   
108  -0.372126  0.098439 -0.604313  0.151024   
114  -0.498631 -0.117300 -0.688648 -0.187253   
96   -0.687026 -0.021327 -0.704064 -0.034429   
115  -0.647436 -0.019638 -0.642163 -0.038314   
106  -0.634887  0.044704 -0.723747  0.060357   
104  -0.656887 -0.077964 -0.676072 -0.103970   
99   -0.280044  0.052743 -0.578388  0.088031   
95   -0.644503 -0.026673 -0.723745 -0.026728   

                                                     A3  \
100   [0.013414, 0.021464, 0.02267, 0.022876, 0.0231...   
102   [0.011727, 0.017246, 0.021203, 0.021615, 0.021...   
1465  [0.009992, 0.01945, 0.021982, 0.022273, 0.0224...   
108   [0.009781, 0.019754, 0.023327, 0.023564, 0.023...   
114   [0.011226, 0.021829, 0.026766, 0.02798, 0.0269...   
96    [0.012993, 0.022425, 0.024989, 0.025044, 0.026...   
115   [0.011378, 0.022022, 0.024566, 0.024305, 0.023...   
106   [0.016849, 0.026814, 0.029573, 0.028311, 0.027...   
104   [0.009977, 0.019977, 0.023832, 0.024862, 0.024...   
99    [0.008261, 0.015829, 0.019215, 0.021177, 0.021...   
95    [0.017352, 0.027657, 0.030311, 0.028882, 0.027...   

                                                     D1  \
100   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
102   [0.0, 0.0001, 0.0001, 0.0001, 0.0002, 0.0001, ...   
1465  [0.0, 0.001, 0.0011, 0.0019, 0.001, 0.0011, 0....   
108   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
114   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
96    [0.0, 0.0001, 0.0001, 0.0004, 0.0002, 0.0003, ...   
115   [0.0, 0.0001, 0.0001, 0.0001, 0.0012, 0.0005, ...   
106   [0.0, 0.0001, 0.0001, 0.0001, 0.0005, 0.0009, ...   
104   [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
99    [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...   
95    [0.0, 0.0003, 0.0004, 0.0009, 0.0004, 0.0002, ...   

                                                     D2  \
100   [0.00175, 0.00451, 0.00605, 0.00585, 0.00708, ...   
102   [0.00227, 0.0065, 0.00635, 0.00573, 0.00592, 0...   
1465  [0.00073, 0.002, 0.00271, 0.0033, 0.00487, 0.0...   
108   [0.00054, 0.00234, 0.00401, 0.00534, 0.00647, ...   
114   [0.00158, 0.00473, 0.00715, 0.00809, 0.00925, ...   
96    [0.00169, 0.00331, 0.00459, 0.00462, 0.00762, ...   
115   [0.00138, 0.00399, 0.00619, 0.00623, 0.00645, ...   
106   [0.00165, 0.00388, 0.00539, 0.00654, 0.00796, ...   
104   [0.00107, 0.00332, 0.00505, 0.006, 0.00729, 0....   
99    [0.00165, 0.00433, 0.00711, 0.00694, 0.00803, ...   
95    [0.00167, 0.00406, 0.00534, 0.00686, 0.00906, ...   

                                                     D3  \
100   [0.00012, 0.000591, 0.001199, 0.001893, 0.0027...   
102   [0.00015, 0.000766, 0.001386, 0.002328, 0.0032...   
1465  [3.2e-05, 0.000166, 0.000468, 0.000992, 0.0016...   
108   [1.4e-05, 0.000117, 0.000433, 0.001004, 0.0017...   
114   [3.7e-05, 0.000395, 0.000988, 0.001959, 0.0030...   
96    [8.7e-05, 0.00057, 0.001067, 0.001509, 0.00225...   
11

In [11]:
df2 = df

In [21]:
min(df[['A3', 'D1', 'D2', 'D3', 'D4']].applymap(len).min())

12

In [29]:
list_lengths = df[['A3', 'D1', 'D2', 'D3', 'D4']].applymap(len)

# Find the row indices with the maximum and minimum list lengths
row_with_max_length = list_lengths.sum(axis=1).idxmax()
row_with_min_length = list_lengths.sum(axis=1).idxmin()

# Get the corresponding rows from the original DataFrame
row_with_max_length_data = df.iloc[row_with_max_length]
row_with_min_length_data = df.iloc[row_with_min_length]

# Find the columns with the maximum and minimum list lengths
max_length_columns = list_lengths.loc[row_with_max_length].idxmax()
min_length_columns = list_lengths.loc[row_with_min_length].idxmin()

# Get the respective lengths of the maximum and minimum list lengths
max_length = list_lengths.loc[row_with_max_length, max_length_columns]
min_length = list_lengths.loc[row_with_min_length, min_length_columns]

print("Row with the highest list length (Row Index:", row_with_max_length, ")")
print(row_with_max_length_data)
print("Columns with the highest list length:", max_length_columns)
print("Length:", max_length)

print("\nRow with the lowest list length (Row Index:", row_with_min_length, ")")
print(row_with_min_length_data)
print("Columns with the lowest list length:", min_length_columns)
print("Length:", min_length)

Row with the highest list length (Row Index: 126 )
class                                              Biplane
path                             ./features/Biplane\D00276
V                                                 0.317499
S                                                -0.242264
c                                                -0.021151
D                                                -0.455042
R                                                 0.235541
E                                                 0.305287
C                                                 0.297418
A3       [0.004609, 0.009604, 0.012367, 0.01425, 0.0157...
D1       [0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, ...
D2       [0.0004, 0.00167, 0.00304, 0.00375, 0.00485, 0...
D3       [1.5e-05, 0.000133, 0.000491, 0.001019, 0.0017...
D4       [7.7e-05, 0.000313, 0.000951, 0.001741, 0.0027...
Name: 126, dtype: object
Columns with the highest list length: D1
Length: 101

Row with the lowest list length (Row Index: 

In [37]:
df[df["path"] == "./features/Car\m1510"]["D1"].iloc[0]

array([0.000e+00, 2.040e-02, 7.110e-02, 1.141e-01, 1.147e-01, 1.297e-01,
       1.772e-01, 1.856e-01, 1.369e-01, 3.200e-02, 1.340e-02, 3.800e-03,
       1.000e-04, 1.000e-04, 1.000e-04, 1.000e-04, 1.000e-04, 1.000e-04,
       1.000e-04, 1.000e-04, 1.000e-04, 1.000e-04, 1.000e-04])

: 

In [16]:
# Determine the maximum number of elements in any list
max_length = 100#max(df.applymap(len).max())

# Expand lists to have the same length
for col in df.columns:
    df[col] = df[col].apply(lambda x: x + [None] * (max_length - len(x)))

# Create new columns for each element in the lists
for i in range(max_length):
    df[f"A3_{i+1}"] = df['A3'].apply(lambda x: x[i])
    df[f"D1_{i+1}"] = df['D1'].apply(lambda x: x[i])
    df[f"D2_{i+1}"] = df['D2'].apply(lambda x: x[i])
    df[f"D3_{i+1}"] = df['D3'].apply(lambda x: x[i])
    df[f"D4_{i+1}"] = df['D4'].apply(lambda x: x[i])

# Drop the original columns with lists
df = df.drop(columns=['A3', 'D1', 'D2', 'D3', 'D4'])

TypeError: can only concatenate str (not "list") to str

In [73]:
#computes euclidean distance between 2 vectors
def euclidean_distance(vector1, vector2):
    euclidean = np.linalg.norm(np.asarray(vector1[2:9]) - np.asarray(vector2[2:9]))
    return euclidean

#computes cosine distance between 2 vectors
def cosine_distance(vector1, vector2):
    one_arr = np.asarray(vector1)
    two_arr = np.asarray(vector2)
    cosine = 1 - ((one_arr @ two_arr) / (np.linalg.norm(one_arr) * np.linalg.norm(two_arr)))
    return cosine

In [234]:

from scipy.spatial.distance import pdist, squareform
from scipy.stats import wasserstein_distance

data = []
data_path = []

dbpath = r"../features/"
for class_folder in os.listdir(dbpath):
    class_folder_path = os.path.join(dbpath, class_folder)
    for obj_file_path in glob.glob(os.path.join(class_folder_path, '*')):
        data.append(np.load(obj_file_path, allow_pickle=True))
        data_path.append(obj_file_path)

def flatten(ndarray):
    new = ndarray[0:7]
    for i in ndarray[7:12]:
        new = np.append(new, i)
    return new

def calculate_distances(target_index, weights1, weights2):
    target = data[target_index]
    target_path = data_path[target_index]

    distances = []
    for i in range(len(data)):
        compare = np.array([target[:7], data[i][:7]])
        cosine_distance = pdist(compare, metric='cosine', w=weights1)[0]
        a3_distance = wasserstein_distance(target[7], data[i][7])
        d1_distance = wasserstein_distance(target[8], data[i][8])
        d2_distance = wasserstein_distance(target[9], data[i][9])
        d3_distance = wasserstein_distance(target[10], data[i][10])
        d4_distance = wasserstein_distance(target[11], data[i][11])
        data_tuple = [data_path[i], np.array([cosine_distance, a3_distance, d1_distance, d2_distance, d3_distance, d4_distance])]
        distances.append(data_tuple)

    norm = [max([x[i] for _, x in distances]) for i in range(6)]
    res = []
    for name, x in distances:
        res.append([name, sum((x / norm) * weights2)])
    res.sort(key=lambda a: a[1])
    return res



In [218]:
def get_class_val(res, class_name):
    weighting = np.arange(len(res))
    has_jet = np.array([(1 if class_name in n else 0) for n, _ in res])
    jet_val = sum(has_jet * weighting) / len(weighting)
    return jet_val

In [329]:
weights1 = None
weights2 = None
val = 50

while val > 45:
    weights1 = np.random.randint(0, 100, size=(7)) / 100
    weights2 = np.random.randint(0, 100, size=(6)) / 100

    results = []
    plane_indexes = range(1269, 1410)[:10]
    for i in plane_indexes:
        results.append(get_class_val(calculate_distances(1400, weights1, weights2), "Jet"))

    val = sum(results) / len(plane_indexes)

print(weights1)
print(weights2)

[0.09 0.91 0.06 0.02 0.04 0.11 0.94]
[0.73 0.98 0.66 0.2  0.64 0.24]
57.012121212121215


In [319]:
res = calculate_distances(1402, weights1, weights2)
print(res[:10])

[['../features/Jet\\m1293', 0.0], ['../features/PlantIndoors\\m1009', 0.34378351466052764], ['../features/PlantIndoors\\m1021', 0.36244850729123607], ['../features/Jet\\m1295', 0.37265108180524664], ['../features/Helicopter\\m1313', 0.3861098753961846], ['../features/Helicopter\\D00502', 0.3915719181449423], ['../features/Cellphone\\D00018', 0.405141707725938], ['../features/Jet\\m1294', 0.4129270729816663], ['../features/Bird\\m43', 0.4250072788866744], ['../features/Jet\\m1252', 0.4250180417808172]]


In [104]:
import numpy as np

X = np.array([[5, 4, 3], [4, 2, 1]])
w = [2, 2, 2]

distances = pdist(X, metric='cosine', w=w)

print(distances)
# change the result to a square matrix
distances = squareform(distances) 
distances

[0.04331923]


array([[0.        , 0.04331923],
       [0.04331923, 0.        ]])

In [ ]:
from sklearn.linear_model import LinearRegression

predictor = LinearRegression(n_jobs=-1)
predictor.fit(X=TRAIN_INPUT, y=TRAIN_OUTPUT)

X_TEST = [[10, 20, 30]]
outcome = predictor.predict(X=X_TEST)
coefficients = predictor.coef_

print('Outcome : {}\nCoefficients : {}'.format(outcome, coefficients))